version: '1'

services:
  db:
    container_name: postgresdb
    image: postgres
    volumes:
      - postgres-db:/var/lib/postgresql/data
      - ./postgresdb:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456
  pgAdmin:
    image: dpage/pgadmin4
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - 80:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=superman@google.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    depends_on:
      - db
volumes:
  postgres-db:
    external: true
